package generator

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/feronski-bkpk/protoc-gen-go/internal/ast"
)

type Generator struct {
	proto *ast.Protocol
}

func NewGenerator(proto *ast.Protocol) *Generator {
	return &Generator{proto: proto}
}

func (g *Generator) Generate() (string, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by protoc-gen-go. DO NOT EDIT.\n")
	buf.WriteString("// source: " + g.proto.Name + "\n\n")
	buf.WriteString("package protocol\n\n")

	needsBinary, needsMath := g.checkNeededImports(g.proto.Fields)

	if needsBinary || needsMath {
		buf.WriteString("import (\n")
		if needsBinary {
			buf.WriteString("    \"encoding/binary\"\n")
		}
		if needsMath {
			buf.WriteString("    \"math\"\n")
		}
		buf.WriteString(")\n\n")
	}

	nestedStructs := g.collectNestedStructs(g.proto.Fields)
	for _, structDef := range nestedStructs {
		structCode, err := g.generateStructDef(structDef.Name, structDef.Fields)
		if err != nil {
			return "", err
		}
		buf.WriteString(structCode)
	}

	structCode, err := g.generateStructDef(g.proto.Name, g.proto.Fields)
	if err != nil {
		return "", err
	}
	buf.WriteString(structCode)

	offsetsCode := g.generateOffsets(g.proto.Name, g.proto.Fields, "", 0)
	buf.WriteString(offsetsCode)

	return buf.String(), nil
}

func (g *Generator) checkNeededImports(fields []ast.Field) (bool, bool) {
	needsBinary := false
	needsMath := false

	for _, field := range fields {
		switch f := field.(type) {
		case *ast.ScalarField:
			switch f.Type {
			case ast.UINT16, ast.UINT32, ast.UINT64, ast.INT16, ast.INT32, ast.INT64:
				needsBinary = true
			case ast.FLOAT32, ast.FLOAT64:
				needsBinary = true
				needsMath = true
			}
		case *ast.StructField:
			b, m := g.checkNeededImports(f.Struct.Fields)
			needsBinary = needsBinary || b
			needsMath = needsMath || m
		case *ast.BitStructField:
			needsBinary = true
		}
	}

	return needsBinary, needsMath
}

type structInfo struct {
	Name   string
	Fields []ast.Field
}

func (g *Generator) collectNestedStructs(fields []ast.Field) []structInfo {
	var structs []structInfo

	for _, field := range fields {
		if structField, ok := field.(*ast.StructField); ok {
			structs = append(structs, structInfo{
				Name:   capitalize(structField.Name),
				Fields: structField.Struct.Fields,
			})
			structs = append(structs, g.collectNestedStructs(structField.Struct.Fields)...)
		}
	}

	return structs
}

func (g *Generator) generateStructDef(name string, fields []ast.Field) (string, error) {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("type %s struct {\n", name))

	for _, field := range fields {
		fieldCode, err := g.fieldToGo(field)
		if err != nil {
			return "", err
		}
		buf.WriteString("    " + fieldCode + "\n")
	}

	buf.WriteString("}\n\n")

	buf.WriteString(g.generateSizeMethod(name, fields))
	buf.WriteString(g.generateMarshalMethod(name, fields))
	buf.WriteString(g.generateUnmarshalMethod(name, fields))

	for _, field := range fields {
		if bitField, ok := field.(*ast.BitStructField); ok {
			buf.WriteString(g.generateBitFieldMethods(name, bitField))
		}
	}

	return buf.String(), nil
}

func (g *Generator) generateBitFieldMethods(structName string, field *ast.BitStructField) string {
	var buf bytes.Buffer
	fieldName := capitalize(field.Name)

	for _, bit := range field.Fields {
		methodName := capitalize(bit.Name)

		buf.WriteString(fmt.Sprintf("func (p *%s) Get%s() bool {\n", structName, methodName))
		buf.WriteString(fmt.Sprintf("    return (p.%s & (1 << %d)) != 0\n", fieldName, bit.Bit))
		buf.WriteString("}\n\n")

		buf.WriteString(fmt.Sprintf("func (p *%s) Set%s(val bool) {\n", structName, methodName))
		buf.WriteString("    if val {\n")
		buf.WriteString(fmt.Sprintf("        p.%s |= (1 << %d)\n", fieldName, bit.Bit))
		buf.WriteString("    } else {\n")
		buf.WriteString(fmt.Sprintf("        p.%s &^= (1 << %d)\n", fieldName, bit.Bit))
		buf.WriteString("    }\n")
		buf.WriteString("}\n\n")
	}

	return buf.String()
}

func (g *Generator) fieldToGo(field ast.Field) (string, error) {
	switch f := field.(type) {
	case *ast.ScalarField:
		return fmt.Sprintf("%s %s", capitalize(f.Name), scalarToGoType(f.Type)), nil
	case *ast.StructField:
		return fmt.Sprintf("%s %s", capitalize(f.Name), capitalize(f.Name)), nil
	case *ast.BitStructField:
		return fmt.Sprintf("%s uint8 // bitstruct", capitalize(f.Name)), nil
	case *ast.BytesField:
		return fmt.Sprintf("%s []byte", capitalize(f.Name)), nil
	default:
		return "", fmt.Errorf("неподдерживаемый тип: %T", field)
	}
}

func (g *Generator) generateOffsets(prefix string, fields []ast.Field, parentPath string, baseOffset int) string {
	var buf bytes.Buffer
	offset := baseOffset

	for _, field := range fields {
		fieldName := capitalize(field.GetName())
		fieldPath := parentPath + fieldName

		switch f := field.(type) {
		case *ast.ScalarField:
			size := f.Type.Size()
			buf.WriteString(fmt.Sprintf("const %s_%s_Offset = %d\n", prefix, fieldPath, offset))
			buf.WriteString(fmt.Sprintf("const %s_%s_Size = %d\n\n", prefix, fieldPath, size))
			offset += size

		case *ast.StructField:
			buf.WriteString(g.generateOffsets(prefix, f.Struct.Fields, fieldPath+"_", offset))
			structSize := g.calculateStructSize(f.Struct.Fields)
			buf.WriteString(fmt.Sprintf("const %s_%s_Offset = %d\n", prefix, fieldPath, offset))
			buf.WriteString(fmt.Sprintf("const %s_%s_Size = %d\n\n", prefix, fieldPath, structSize))
			offset += structSize

		case *ast.BitStructField:
			buf.WriteString(fmt.Sprintf("const %s_%s_Offset = %d\n", prefix, fieldPath, offset))
			buf.WriteString(fmt.Sprintf("const %s_%s_Size = 1\n\n", prefix, fieldPath))
			offset += 1

		case *ast.BytesField:
			buf.WriteString(fmt.Sprintf("// %s_%s has dynamic offset\n", prefix, fieldPath))
		}
	}

	return buf.String()
}

func (g *Generator) calculateStructSize(fields []ast.Field) int {
	size := 0
	for _, field := range fields {
		size += field.GetSize()
	}
	return size
}

func (g *Generator) generateSizeMethod(structName string, fields []ast.Field) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (p *%s) Size() int {\n", structName))
	buf.WriteString("    size := 0\n")

	for _, field := range fields {
		fieldName := capitalize(field.GetName())

		switch f := field.(type) {
		case *ast.ScalarField:
			buf.WriteString(fmt.Sprintf("    size += %d // %s\n", f.Type.Size(), fieldName))
		case *ast.StructField:
			buf.WriteString(fmt.Sprintf("    size += p.%s.Size()\n", fieldName))
		case *ast.BitStructField:
			buf.WriteString(fmt.Sprintf("    size += 1 // %s (bitstruct)\n", fieldName))
		case *ast.BytesField:
			if f.Condition != nil {
				buf.WriteString(fmt.Sprintf("    if %s {\n", g.conditionToGo(f.Condition)))
				buf.WriteString(fmt.Sprintf("        size += len(p.%s)\n", fieldName))
				buf.WriteString("    }\n")
			} else {
				buf.WriteString(fmt.Sprintf("    size += len(p.%s)\n", fieldName))
			}
		}
	}

	buf.WriteString("    return size\n")
	buf.WriteString("}\n\n")

	return buf.String()
}

func (g *Generator) generateMarshalMethod(structName string, fields []ast.Field) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (p *%s) MarshalBinary() ([]byte, error) {\n", structName))
	buf.WriteString("    buf := make([]byte, p.Size())\n")
	buf.WriteString("    offset := 0\n\n")

	for _, field := range fields {
		fieldName := capitalize(field.GetName())

		switch f := field.(type) {
		case *ast.ScalarField:
			buf.WriteString(g.generateMarshalScalar(fieldName, f.Type))
		case *ast.StructField:
			buf.WriteString(fmt.Sprintf("    structData, err := p.%s.MarshalBinary()\n", fieldName))
			buf.WriteString("    if err != nil {\n        return nil, err\n    }\n")
			buf.WriteString("    copy(buf[offset:], structData)\n")
			buf.WriteString("    offset += len(structData)\n\n")
		case *ast.BitStructField:
			buf.WriteString(fmt.Sprintf("    buf[offset] = p.%s\n", fieldName))
			buf.WriteString("    offset += 1\n\n")
		case *ast.BytesField:
			if f.Condition != nil {
				buf.WriteString(fmt.Sprintf("    if %s {\n", g.conditionToGo(f.Condition)))
				buf.WriteString(fmt.Sprintf("        copy(buf[offset:], p.%s)\n", fieldName))
				buf.WriteString(fmt.Sprintf("        offset += len(p.%s)\n", fieldName))
				buf.WriteString("    }\n\n")
			} else {
				buf.WriteString(fmt.Sprintf("    copy(buf[offset:], p.%s)\n", fieldName))
				buf.WriteString(fmt.Sprintf("    offset += len(p.%s)\n\n", fieldName))
			}
		}
	}

	buf.WriteString("    return buf, nil\n")
	buf.WriteString("}\n\n")

	return buf.String()
}

func (g *Generator) generateMarshalScalar(fieldName string, scalarType ast.ScalarType) string {
	var buf bytes.Buffer

	switch scalarType {
	case ast.UINT8, ast.INT8:
		buf.WriteString(fmt.Sprintf("    buf[offset] = byte(p.%s)\n", fieldName))
		buf.WriteString("    offset += 1\n\n")
	case ast.UINT16:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint16(buf[offset:], p.%s)\n", fieldName))
		buf.WriteString("    offset += 2\n\n")
	case ast.INT16:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint16(buf[offset:], uint16(p.%s))\n", fieldName))
		buf.WriteString("    offset += 2\n\n")
	case ast.UINT32:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint32(buf[offset:], p.%s)\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.INT32:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint32(buf[offset:], uint32(p.%s))\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.UINT64:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint64(buf[offset:], p.%s)\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	case ast.INT64:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint64(buf[offset:], uint64(p.%s))\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	case ast.FLOAT32:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint32(buf[offset:], math.Float32bits(p.%s))\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.FLOAT64:
		buf.WriteString(fmt.Sprintf("    binary.BigEndian.PutUint64(buf[offset:], math.Float64bits(p.%s))\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	}

	return buf.String()
}

func (g *Generator) generateUnmarshalMethod(structName string, fields []ast.Field) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (p *%s) UnmarshalBinary(data []byte) error {\n", structName))
	buf.WriteString("    offset := 0\n\n")

	for _, field := range fields {
		fieldName := capitalize(field.GetName())

		switch f := field.(type) {
		case *ast.ScalarField:
			buf.WriteString(g.generateUnmarshalScalar(fieldName, f.Type))
		case *ast.StructField:
			buf.WriteString(fmt.Sprintf("    if err := p.%s.UnmarshalBinary(data[offset:]); err != nil {\n        return err\n    }\n", fieldName))
			buf.WriteString(fmt.Sprintf("    offset += p.%s.Size()\n\n", fieldName))
		case *ast.BitStructField:
			buf.WriteString(fmt.Sprintf("    p.%s = data[offset]\n", fieldName))
			buf.WriteString("    offset += 1\n\n")
		case *ast.BytesField:
			if f.Condition != nil {
				buf.WriteString(fmt.Sprintf("    if %s {\n", g.conditionToGo(f.Condition)))
				if f.LengthFrom != "" {
					lengthField := capitalize(f.LengthFrom)
					buf.WriteString(fmt.Sprintf("        p.%s = make([]byte, p.%s)\n", fieldName, lengthField))
					buf.WriteString(fmt.Sprintf("        copy(p.%s, data[offset:offset+int(p.%s)])\n", fieldName, lengthField))
					buf.WriteString(fmt.Sprintf("        offset += int(p.%s)\n", lengthField))
				}
				buf.WriteString("    }\n\n")
			} else {
				if f.LengthFrom != "" {
					lengthField := capitalize(f.LengthFrom)
					buf.WriteString(fmt.Sprintf("    p.%s = make([]byte, p.%s)\n", fieldName, lengthField))
					buf.WriteString(fmt.Sprintf("    copy(p.%s, data[offset:offset+int(p.%s)])\n", fieldName, lengthField))
					buf.WriteString(fmt.Sprintf("    offset += int(p.%s)\n\n", lengthField))
				}
			}
		}
	}

	buf.WriteString("    return nil\n")
	buf.WriteString("}\n\n")

	return buf.String()
}

func (g *Generator) generateUnmarshalScalar(fieldName string, scalarType ast.ScalarType) string {
	var buf bytes.Buffer

	switch scalarType {
	case ast.UINT8:
		buf.WriteString(fmt.Sprintf("    p.%s = data[offset]\n", fieldName))
		buf.WriteString("    offset += 1\n\n")
	case ast.INT8:
		buf.WriteString(fmt.Sprintf("    p.%s = int8(data[offset])\n", fieldName))
		buf.WriteString("    offset += 1\n\n")
	case ast.UINT16:
		buf.WriteString(fmt.Sprintf("    p.%s = binary.BigEndian.Uint16(data[offset:])\n", fieldName))
		buf.WriteString("    offset += 2\n\n")
	case ast.INT16:
		buf.WriteString(fmt.Sprintf("    p.%s = int16(binary.BigEndian.Uint16(data[offset:]))\n", fieldName))
		buf.WriteString("    offset += 2\n\n")
	case ast.UINT32:
		buf.WriteString(fmt.Sprintf("    p.%s = binary.BigEndian.Uint32(data[offset:])\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.INT32:
		buf.WriteString(fmt.Sprintf("    p.%s = int32(binary.BigEndian.Uint32(data[offset:]))\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.UINT64:
		buf.WriteString(fmt.Sprintf("    p.%s = binary.BigEndian.Uint64(data[offset:])\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	case ast.INT64:
		buf.WriteString(fmt.Sprintf("    p.%s = int64(binary.BigEndian.Uint64(data[offset:]))\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	case ast.FLOAT32:
		buf.WriteString(fmt.Sprintf("    p.%s = math.Float32frombits(binary.BigEndian.Uint32(data[offset:]))\n", fieldName))
		buf.WriteString("    offset += 4\n\n")
	case ast.FLOAT64:
		buf.WriteString(fmt.Sprintf("    p.%s = math.Float64frombits(binary.BigEndian.Uint64(data[offset:]))\n", fieldName))
		buf.WriteString("    offset += 8\n\n")
	}

	return buf.String()
}

func (g *Generator) conditionToGo(cond *ast.Condition) string {
	return fmt.Sprintf("p.%s %s %d", capitalize(cond.Field), cond.Operator, cond.Value)
}

func scalarToGoType(t ast.ScalarType) string {
	return string(t)
}

func capitalize(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
